Minus
onlydianaT/teamWork pull request #2
Opened 2022-07-27 09:32 UTC by onlydianaT

1. Added: line 94 (because now we can input negative amount of product, so we need to check it) , selected cod with **
```java
if (quantity[i] != 0**&&quantity[i] >0**)
```
3.Added: line 105 (just to see what kind of price - with discount or not), selected cod with **
```java
System.out.println("**Discount price:** " + products[i] + " " + quantity[i] + " items " + prices[i] + " rub/item, " + sum + " rub " + " totally");
                    
```

2022-07-27 17:54 UTC, ElzaKoylubaeva requested changes

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> -            if (itemOfProduct < 0 || amountOfProduct < 0) {
оставить проверку на itemOfProduct < 0

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +                quantity[itemOfProduct] += amountOfProduct;
Убрать строку, т.к. установка в 0 есть ранее

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +            if (amountOfProduct != 0) {
Сделать через else

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +            if (totalSum > 0) {
нет необходимости делать эту проверку, общая сумма не может быть отрицательной, т. к. расчет идет для quantity[i] > 0

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +            if (amountOfProduct < 0) {
Зачем выводить эту информацию на консоль?

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +            if (quantity[i] != 0 && quantity[i] > 0) {
в условии достаточно указать quantity[i] > 0.

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +            if (amountOfProduct == 0) {
Вводим еще проверку на отрицательное значение количества товара, для этого добавляем ее через исключающее или в тот же if с проверкой на равенство нулю
boolean isQuantityNegative = amountOfProduct < 0 && (quantity[itemOfProduct] + amountOfProduct) < 0;
            if (amountOfProduct == 0 || isQuantityNegative)

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +                totalSum = 0;
Удалить строчку, вынесем за пределы while(true)  и будем считать в цикле fori ниже

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +                totalSum += amountOfProduct * prices[itemOfProduct];
Удалить строчку, вынесем за пределы while(true)  и будем считать в цикле fori ниже

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +        int totalSum = 0;
Удалить строчку, объявим перед циклом fori ниже, там где будем его считать

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +        totalSum = 0;
Здесь объявляем int totalSum = 0;

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +                System.out.println("Price without discount: "+ products[i] + " " + quantity[i] + " items " + prices[i] + " rub/item, " + (quantity[i] * prices[i]) + " rub " + " totally");}
Предлагаю не выводить на консоль дважды сумму для продуктов со скидкой Просто вывести как это было изначально. Читается плохо, выглядит избыточно. Если все же есть желание, то следует sout  с этой информацией поместить прямо в if (promo)  и в той же строке продукта указать цену со скидкой и без. В else  соответственно будет вывод в консоль в первоначальном виде.

2022-07-27 17:54 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +                if (quantity[i] != 0&&quantity[i] > 0) {
Этот if повторяет логику вышестоящего. Он не нужен.

2022-07-27 20:17 UTC, onlydianaT commented on src/ru/koylubaevaem/task3/Main.java
> -            if (itemOfProduct < 0 || amountOfProduct < 0) {
Да, если оставить только itemOfProduct < 0 + добавить в 67 строке System.out.println("Data were entered incorrectly. The position of product or its amount " +
                        "can't be negative **or zero**");

2022-07-27 20:17 UTC, onlydianaT commented on src/ru/koylubaevaem/task3/Main.java
> -                        "can't be negative");
can't be negative **or zero**

2022-07-27 20:17 UTC, onlydianaT commented on src/ru/koylubaevaem/task3/Main.java
> +            if (amountOfProduct == 0) {
Нет, если введем сюда еще проверку на отрицательное значение, то будет обнуляться все. А смысл в том, что вводя отрицательное количество товара, мы должны отнять его от общего количества товара уже введенного по той или иной позиции.

2022-07-27 20:17 UTC, onlydianaT commented on src/ru/koylubaevaem/task3/Main.java
> +            if (quantity[i] != 0 && quantity[i] > 0) {
Нет, так как будет выводить и для отрицательного количества товара информацию, в т.ч. отрицательную сумму. Выше мы это не делаем: boolean isQuantityNegative = amountOfProduct < 0 && (quantity[itemOfProduct] + amountOfProduct) < 0;
if (amountOfProduct == 0 || isQuantityNegative)

Поэтому это условие необходимо оставить так.

2022-07-27 20:17 UTC, onlydianaT commented on src/ru/koylubaevaem/task3/Main.java
> +                System.out.println("Price without discount: "+ products[i] + " " + quantity[i] + " items " + prices[i] + " rub/item, " + (quantity[i] * prices[i]) + " rub " + " totally");}
Считаю, что информацию со скидкой или без нужно оставить. Особенно важно читать такое в чеках для бабушек))) Сделали скидку или нет.

2022-07-27 20:17 UTC, onlydianaT commented on src/ru/koylubaevaem/task3/Main.java
> +                if (quantity[i] != 0&&quantity[i] > 0) {
да, задвоилось.

2022-07-27 20:17 UTC, onlydianaT commented on src/ru/koylubaevaem/task3/Main.java
> +            if (amountOfProduct < 0) {
Предлагаю оставить, т.к. покупатель мог ошибочно ввести отрицательное количество товара и не понять почему он не вошел в корзину и в общую стоимость:

for (int i = 0; i < quantity.length; i++) {
            if (quantity[i] < 0) {
                System.out.println("Amount of product for " + products[i]+ "can't be negative");

        }

2022-07-28 06:12 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> -            if (itemOfProduct < 0 || amountOfProduct < 0) {
Верно, только необходимо убрать количество товара из сообщения.

2022-07-28 06:16 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +            if (amountOfProduct < 0) {
Для этого мной была предложена проверка при установке количества в ноль. И ведь если сделать так, то человек не сможет получить информацию по итоговой сумме, что не соответствует задаче.

2022-07-28 06:19 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +            if (quantity[i] != 0 && quantity[i] > 0) {
не верно. quantity[i] > 0 - условие значит -> что рассматриваем только все значения больше нуля, но не включая ноль. Поэтому этого условия достаточно

2022-07-28 06:25 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +            if (amountOfProduct == 0) {
А если количество товара было введено сначала 5, а потом -10?  Чтобы в quantity не попало отрицательное значение (в корзине по логике не может быть отрицательное значение)  необходима эта проверка. При введении например 10 и -5 не будет обнуляться, обнуляться будет лишь при получении отрицательного значения в корзине .

2022-07-28 06:30 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +                System.out.println("Price without discount: "+ products[i] + " " + quantity[i] + " items " + prices[i] + " rub/item, " + (quantity[i] * prices[i]) + " rub " + " totally");}
Тогда обе суммы указываем в одной строке. в логике if (promo)

2022-07-28 12:27 UTC, ElzaKoylubaeva requested changes

2022-07-28 12:27 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
>                  System.out.println("Data were entered incorrectly. The position of product or its amount " +
or its amount - необходимо удалить, так как amount может быть отрицательным

2022-07-28 12:27 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +            int totalSum = 0;
удалить строку int totalSum = 0;

2022-07-28 12:27 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +        String nameOfGood;
для чего вынесла сюда переменную?

2022-07-28 12:27 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +                    System.out.println("Discount price: " + products[i] + " " + quantity[i] + " items " + prices[i] + " rub/item, " + sum + " rub " + " totally, " + "without discount: " + quantity[i]
" rub " + " totally, " + "without discount: " - загнать в одни ковычки, " rub " - добавить в конец

2022-07-28 12:27 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
> +                    System.out.println("Price without discount : " + products[i] + " " + quantity[i] + " items " + prices[i] + " rub/item, " + sum + " rub " + " totally");
Здесь не нужно писать что без скидки, потому, что для этих товаров ее нет

2022-07-28 12:27 UTC, ElzaKoylubaeva commented on src/ru/koylubaevaem/task3/Main.java
>                  System.out.println("Data were entered incorrectly. The position of product or its amount " +
Более того, так как мы не проверяем теперь amountOfProduct на отрицательное значение, лучше этот if объединить с  if (itemOfProduct > products.length) , то есть проверить условие itemOfProduct < 0 через  или || .

2022-07-28 12:35 UTC, onlydianaT commented on src/ru/koylubaevaem/task3/Main.java
> +        String nameOfGood;
Не выносила, может что-то сдвинулось

2022-07-28 14:03 UTC, merged